// Generated by face/export_esp32.py — do not edit by hand.
// The source is the set of PNGs in face/frames/.

#pragma once
#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const uint8_t eye_normal_png[];
extern const size_t eye_normal_png_len;
extern const uint8_t eye_normal_left_png[];
extern const size_t eye_normal_left_png_len;
extern const uint8_t eye_normal_right_png[];
extern const size_t eye_normal_right_png_len;
extern const uint8_t eye_normal_down_png[];
extern const size_t eye_normal_down_png_len;
extern const uint8_t eye_normal_half_png[];
extern const size_t eye_normal_half_png_len;
extern const uint8_t eye_normal_closed_png[];
extern const size_t eye_normal_closed_png_len;
extern const uint8_t eye_listening_png[];
extern const size_t eye_listening_png_len;
extern const uint8_t eye_listening_left_png[];
extern const size_t eye_listening_left_png_len;
extern const uint8_t eye_listening_right_png[];
extern const size_t eye_listening_right_png_len;
extern const uint8_t eye_listening_down_png[];
extern const size_t eye_listening_down_png_len;
extern const uint8_t eye_listening_half_png[];
extern const size_t eye_listening_half_png_len;
extern const uint8_t eye_listening_closed_png[];
extern const size_t eye_listening_closed_png_len;

#ifdef __cplusplus
}
#endif
