// Generated by face/export_esp32.py — do not edit by hand.
// The source is the set of PNGs in face/frames/.

#pragma once
#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

#define MOUTH_X 68
#define MOUTH_Y 160
#define MOUTH_W 104
#define MOUTH_H 45
#define MOUTH_TALK_N 8
#define MOUTH_GESTURE_N 11

// Which mouth each emotion uses. The table is generated by the
// exporter so the firmware has no copy of it that could drift.
typedef struct { const char* emotion; unsigned char gesture; } MouthEmotion;
extern const MouthEmotion mouth_emotions[];
extern const size_t mouth_emotions_n;
extern const uint8_t* const mouth_talk_png[MOUTH_TALK_N];
extern const size_t mouth_talk_len[MOUTH_TALK_N];
extern const uint8_t* const mouth_gesture_png[MOUTH_GESTURE_N];
extern const size_t mouth_gesture_len[MOUTH_GESTURE_N];

#ifdef __cplusplus
}
#endif
